services:
  frontend:
    image: your-frontend-image-name:latest
    ports:
      - "3000:3000"  # Adjust the port mappings as needed (Host:Container)
    volumes:
      - ./src:/app/src  # Mount your local source code directory into the container
    environment:
      - NODE_ENV=production  # Set the environment variables as needed for your frontend
      